import type { Metadata } from "next";
import { Cinzel_Decorative, Roboto } from "next/font/google";
import "../../globals.css";
import Header from "../../components/Header";

export const cinzel = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const roboto_Mono = Roboto({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Weebefied",
  description: "Generated by create next app",
  icons: "/logo-2-1_no-bg.png",
};
export default function RestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
