import type { Metadata } from "next";
import { Cinzel_Decorative, Roboto } from "next/font/google";
import "../../globals.css";
import SliderContent from "@/app/components/Slider";
import Slider from "@/app/components/Slider";
import AuthHeader from "@/app/components/AuthHeader";

export const cinzel = Cinzel_Decorative({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const roboto_Mono = Roboto({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Weebefied",
  description: "Generated by create next app",
  icons: "/logo-2-1_no-bg.png",
};
export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className="dark">
    // <body className={`${roboto_Mono.className} antialiased`}>
    <div className="flex flex-row h-svh w-svw bg-[url('/login-5.jpg')] bg-cover bg-center relative">
      <AuthHeader sx="absolute top-0 left-0 custom-pointer z-20" />
      <div className="hidden lg:block w-full">{/* <Slider /> */}</div>
      {children}
    </div>

    //  </body>
    // </html>
  );
}
