/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSearchIndexRouteImport } from './routes/_layout/search/index'
import { Route as LayoutHomeIndexRouteImport } from './routes/_layout/home/index'
import { Route as LayoutGenreIndexRouteImport } from './routes/_layout/genre/index'
import { Route as LayoutWatchIdRouteImport } from './routes/_layout/watch/$id'
import { Route as LayoutInfoIdRouteImport } from './routes/_layout/info/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSearchIndexRoute = LayoutSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHomeIndexRoute = LayoutHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGenreIndexRoute = LayoutGenreIndexRouteImport.update({
  id: '/genre/',
  path: '/genre/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWatchIdRoute = LayoutWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInfoIdRoute = LayoutInfoIdRouteImport.update({
  id: '/info/$id',
  path: '/info/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/info/$id': typeof LayoutInfoIdRoute
  '/watch/$id': typeof LayoutWatchIdRoute
  '/genre': typeof LayoutGenreIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/search': typeof LayoutSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/info/$id': typeof LayoutInfoIdRoute
  '/watch/$id': typeof LayoutWatchIdRoute
  '/genre': typeof LayoutGenreIndexRoute
  '/home': typeof LayoutHomeIndexRoute
  '/search': typeof LayoutSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/info/$id': typeof LayoutInfoIdRoute
  '/_layout/watch/$id': typeof LayoutWatchIdRoute
  '/_layout/genre/': typeof LayoutGenreIndexRoute
  '/_layout/home/': typeof LayoutHomeIndexRoute
  '/_layout/search/': typeof LayoutSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/info/$id' | '/watch/$id' | '/genre' | '/home' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/info/$id' | '/watch/$id' | '/genre' | '/home' | '/search'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/info/$id'
    | '/_layout/watch/$id'
    | '/_layout/genre/'
    | '/_layout/home/'
    | '/_layout/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/search/': {
      id: '/_layout/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof LayoutSearchIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/home/': {
      id: '/_layout/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutHomeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/genre/': {
      id: '/_layout/genre/'
      path: '/genre'
      fullPath: '/genre'
      preLoaderRoute: typeof LayoutGenreIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/watch/$id': {
      id: '/_layout/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof LayoutWatchIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/info/$id': {
      id: '/_layout/info/$id'
      path: '/info/$id'
      fullPath: '/info/$id'
      preLoaderRoute: typeof LayoutInfoIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutInfoIdRoute: typeof LayoutInfoIdRoute
  LayoutWatchIdRoute: typeof LayoutWatchIdRoute
  LayoutGenreIndexRoute: typeof LayoutGenreIndexRoute
  LayoutHomeIndexRoute: typeof LayoutHomeIndexRoute
  LayoutSearchIndexRoute: typeof LayoutSearchIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutInfoIdRoute: LayoutInfoIdRoute,
  LayoutWatchIdRoute: LayoutWatchIdRoute,
  LayoutGenreIndexRoute: LayoutGenreIndexRoute,
  LayoutHomeIndexRoute: LayoutHomeIndexRoute,
  LayoutSearchIndexRoute: LayoutSearchIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
