FROM postgres:15

RUN apt-get update \
  && apt-get install -y postgresql-15-cron \
  && rm -rf /var/lib/apt/lists/*

# Enable pg_cron at startup
CMD ["postgres", "-c", "shared_preload_libraries=pg_cron"]
