import type { Metadata } from "next";
import {Cinzel_Decorative,Roboto} from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "./libs/theme";

export const cinzel = Cinzel_Decorative({
    variable: '--font-cinzel',
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap', 
  });

export const roboto_Mono=Roboto({
    variable: '--font-roboto-mono',
    subsets: ['latin'],
    weight: ['400', '700'],
    display: 'swap', 
  });
export const metadata: Metadata = {
  title: "Otaku Guild",
  description: "Generated by create next app",
  icons: "/Otaku_Guild-no-bg.png",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto_Mono.className} antialiased`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
          {children}
          </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
